name: Refresh Performance History

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Mondays at 06:00 UTC

jobs:
  refresh:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          SOLR_URL: ${{ secrets.SOLR_URL }}
        run: |
          bash ./tools/sync.sh

      - name: Commit and push changes
        run: |
          git config user.email "actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git add Programs/xml Programs/json || true
          if ! git diff --cached --quiet; then
            git commit -m "Automated refresh"
            git push
          else
            echo "No changes to commit."
